from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

# Import the app's Base and every model so `target_metadata` reflects the
# actual current schema for autogenerate — do not maintain a second,
# hand-written schema definition here.
from app.database import Base, DATABASE_URL
from app.models import (  # noqa: F401
    Alert,
    DataSource,
    IngestionRun,
    LandslideEvent,
    MonitoringRegion,
    RainfallObservation,
    Report,
    RiskUpdateLog,
    WeatherObservation,
    Zone,
)

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Read the connection URL from the app's own configuration (DATABASE_URL
# env var) rather than a hardcoded value in alembic.ini — keeps a single
# source of truth for "which database" between the app and migrations.
config.set_main_option("sqlalchemy.url", DATABASE_URL)

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


# The postgis/postgis image's default template bundles the postgis_tiger_geocoder
# and postgis_topology extensions, which add dozens of their own tables
# (tiger geocoding lookups, topology.*, spatial_ref_sys, etc.). None of
# those belong to this application — autogenerate must never propose
# dropping or altering them. Whitelisting our own table names is more
# robust here than trying to exclude every extension table by name/schema.
OUR_TABLES = {
    "zones",
    "alerts",
    "reports",
    "weather_observations",
    "monitoring_regions",
    "landslide_events",
    "data_sources",
    "ingestion_runs",
    "rainfall_observations",
    "risk_update_logs",
}


def include_object(object, name, type_, reflected, compare_to):
    if type_ == "table":
        return name in OUR_TABLES
    if type_ == "index":
        # Manually-managed GIST spatial indexes: the model sets
        # spatial_index=False on the Geometry column (to avoid GeoAlchemy2
        # auto-creating a conflicting index of the same name), but that
        # also makes the autogenerate comparator think "no index should
        # exist" and propose dropping the one this migration created by
        # hand. Exclude them from comparison entirely — they are
        # intentional and never autogenerated.
        if name and name.startswith("idx_") and name.endswith("_geom"):
            return False
        table = getattr(object, "table", None)
        if table is not None:
            return table.name in OUR_TABLES
        return True
    if type_ in ("unique_constraint", "foreign_key_constraint", "check_constraint"):
        table = getattr(object, "table", None)
        if table is not None:
            return table.name in OUR_TABLES
    return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
