"""initial schema

Revision ID: 5e8df061f40b
Revises: 
Create Date: 2026-08-30 14:20:32.966573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5e8df061f40b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `IF NOT EXISTS` makes this safe to run against a database that
    # already has PostGIS installed (e.g. the postgis/postgis image
    # enables it by default) — it will not fail or reinitialize anything.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landslide_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landslide_events_event_date'), 'landslide_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_landslide_events_id'), 'landslide_events', ['id'], unique=False)
    op.create_index(op.f('ix_landslide_events_latitude'), 'landslide_events', ['latitude'], unique=False)
    op.create_index(op.f('ix_landslide_events_longitude'), 'landslide_events', ['longitude'], unique=False)
    op.create_index(op.f('ix_landslide_events_source_id'), 'landslide_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_landslide_events_state'), 'landslide_events', ['state'], unique=False)
    # GIST spatial index — GeoAlchemy2's automatic index-on-create is
    # disabled (spatial_index=False) so this migration is the single
    # source of truth for it.
    op.create_index('idx_landslide_events_geom', 'landslide_events', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('monitoring_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('region_type', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry_type', sa.String(), nullable=True),
    sa.Column('geometry_data', sa.JSON(), nullable=True),
    sa.Column('is_landslide_prone', sa.Boolean(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_regions_id'), 'monitoring_regions', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_regions_name'), 'monitoring_regions', ['name'], unique=False)
    op.create_index(op.f('ix_monitoring_regions_source_id'), 'monitoring_regions', ['source_id'], unique=False)
    op.create_index(op.f('ix_monitoring_regions_state'), 'monitoring_regions', ['state'], unique=False)
    op.create_index('idx_monitoring_regions_geom', 'monitoring_regions', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('rainfall_24h', sa.Float(), nullable=False),
    sa.Column('rainfall_7d', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('slope', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=False),
    sa.Column('vegetation', sa.Float(), nullable=False),
    sa.Column('historical_landslide', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('rainfall_24h', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('observed_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_id'), 'weather_observations', ['id'], unique=False)
    op.create_index(op.f('ix_weather_observations_zone_id'), 'weather_observations', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observations_zone_id'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_monitoring_regions_state'), table_name='monitoring_regions')
    op.drop_index(op.f('ix_monitoring_regions_source_id'), table_name='monitoring_regions')
    op.drop_index(op.f('ix_monitoring_regions_name'), table_name='monitoring_regions')
    op.drop_index(op.f('ix_monitoring_regions_id'), table_name='monitoring_regions')
    op.drop_index('idx_monitoring_regions_geom', table_name='monitoring_regions', postgresql_using='gist')
    op.drop_table('monitoring_regions')
    op.drop_index('idx_landslide_events_geom', table_name='landslide_events', postgresql_using='gist')
    op.drop_index(op.f('ix_landslide_events_state'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_source_id'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_longitude'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_latitude'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_id'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_event_date'), table_name='landslide_events')
    op.drop_table('landslide_events')
    # ### end Alembic commands ###
