"""phase11 rainfall station id

Revision ID: 70468efec21a
Revises: fda23df41b27
Create Date: 2026-08-31 01:46:37.938921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70468efec21a'
down_revision: Union[str, None] = 'fda23df41b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rainfall_observations', sa.Column('station_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_rainfall_observations_station_id'), 'rainfall_observations', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rainfall_observations_station_id'), table_name='rainfall_observations')
    op.drop_column('rainfall_observations', 'station_id')
    # ### end Alembic commands ###
