"""phase16 alert lifecycle and risk update log

Revision ID: f504451cd19f
Revises: 70468efec21a
Create Date: 2026-08-31 02:17:12.309533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f504451cd19f'
down_revision: Union[str, None] = '70468efec21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_update_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('data_availability', sa.JSON(), nullable=False),
    sa.Column('prediction_source', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_update_logs_created_at'), 'risk_update_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_update_logs_id'), 'risk_update_logs', ['id'], unique=False)
    op.create_index(op.f('ix_risk_update_logs_zone_id'), 'risk_update_logs', ['zone_id'], unique=False)
    # server_default backfills existing rows (this table is not empty in
    # every deployment) — matches the model's Python-level default="active".
    op.add_column('alerts', sa.Column('status', sa.String(), nullable=False, server_default='active'))
    op.add_column('alerts', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    # Backfill status/resolved_at for existing rows from the pre-existing
    # is_active flag — an already-inactive alert is "resolved", not "active".
    op.execute(
        "UPDATE alerts SET status = 'resolved', resolved_at = created_at WHERE is_active = false"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'acknowledged_at')
    op.drop_column('alerts', 'reason')
    op.drop_column('alerts', 'risk_score')
    op.drop_column('alerts', 'status')
    op.drop_index(op.f('ix_risk_update_logs_zone_id'), table_name='risk_update_logs')
    op.drop_index(op.f('ix_risk_update_logs_id'), table_name='risk_update_logs')
    op.drop_index(op.f('ix_risk_update_logs_created_at'), table_name='risk_update_logs')
    op.drop_table('risk_update_logs')
    # ### end Alembic commands ###
