"""phase9 data sources rainfall ingestion runs

Revision ID: fda23df41b27
Revises: 5e8df061f40b
Create Date: 2026-08-30 15:45:53.790444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'fda23df41b27'
down_revision: Union[str, None] = '5e8df061f40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('official_source_url', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('citation', sa.String(), nullable=True),
    sa.Column('geographic_coverage', sa.String(), nullable=True),
    sa.Column('temporal_coverage', sa.String(), nullable=True),
    sa.Column('access_method', sa.String(), nullable=True),
    sa.Column('local_file_name', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_version', sa.String(), nullable=True),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.String(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('limitations', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_category'), 'data_sources', ['category'], unique=False)
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_source_id'), 'data_sources', ['source_id'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('valid_records', sa.Integer(), nullable=True),
    sa.Column('invalid_records', sa.Integer(), nullable=True),
    sa.Column('inserted', sa.Integer(), nullable=True),
    sa.Column('duplicates', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_id'), 'ingestion_runs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_source_id'), 'ingestion_runs', ['source_id'], unique=False)
    op.create_table('rainfall_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('observed_date', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rainfall_observations_id'), 'rainfall_observations', ['id'], unique=False)
    op.create_index(op.f('ix_rainfall_observations_latitude'), 'rainfall_observations', ['latitude'], unique=False)
    op.create_index(op.f('ix_rainfall_observations_longitude'), 'rainfall_observations', ['longitude'], unique=False)
    op.create_index(op.f('ix_rainfall_observations_observed_date'), 'rainfall_observations', ['observed_date'], unique=False)
    op.create_index(op.f('ix_rainfall_observations_source_id'), 'rainfall_observations', ['source_id'], unique=False)
    # GIST spatial index — GeoAlchemy2's automatic index-on-create is
    # disabled (spatial_index=False) so this migration is the single
    # source of truth for it, same as the initial schema migration.
    op.create_index('idx_rainfall_observations_geom', 'rainfall_observations', ['geom'], unique=False, postgresql_using='gist')
    op.add_column('landslide_events', sa.Column('district', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landslide_events', 'district')
    op.drop_index('idx_rainfall_observations_geom', table_name='rainfall_observations', postgresql_using='gist')
    op.drop_index(op.f('ix_rainfall_observations_source_id'), table_name='rainfall_observations')
    op.drop_index(op.f('ix_rainfall_observations_observed_date'), table_name='rainfall_observations')
    op.drop_index(op.f('ix_rainfall_observations_longitude'), table_name='rainfall_observations')
    op.drop_index(op.f('ix_rainfall_observations_latitude'), table_name='rainfall_observations')
    op.drop_index(op.f('ix_rainfall_observations_id'), table_name='rainfall_observations')
    op.drop_table('rainfall_observations')
    op.drop_index(op.f('ix_ingestion_runs_source_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_data_sources_source_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_category'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
